### ISSUE TITLE
Update the data

### ISSUE THREAD

**Issue by alizahidraja** [MohammedArab1/ThaqalaynAPI#2]
Salam!

Love the work here! I am building a dataset on kaggle and just wanted to ask if you can update the data in your rest API as the data on the website seems to be updated and contains some books which are not in the API

Let me know if this will be possible, thanks in advnace!

**Comment by MohammedArab1** [comment]
Wa Alaykum Al Salam,

Unfortunately, after Thaqalayn updated their UI the web scraper stopped working. I haven't had the chance to work on it more or look at alternative ways to fetch the data. InshAllah after the month of Ramadan I will try to take a look but I can't promise anything.

You're welcome to open up any pull requests :) 

Wa Salam.

**Comment by alizahidraja** [comment]
Don't worry brother I understand, I will try my best to work on it and update you! Thankyou for the quick response!

Hope you have a great remaining Ramadan & Eid :D
