### ISSUE TITLE
Books cover

### ISSUE THREAD

**Issue by sayyid5416** [MohammedArab1/ThaqalaynAPI#5]
Assalam! 

Can you also return the cover of the book in `/allbooks` endpoint? 

![Screenshot_20241005-122301_Edge](https://github.com/user-attachments/assets/20eb2871-fd65-42d7-963b-6cb782828f1c)

I'm talking about these ☝️ book covers. 

Nice work btw ❤️

**Comment by sayyid5416** [comment]
Also, I think `translator` should also be returned with this data

**Comment by MohammedArab1** [comment]
Wa Alaykum al Salam,

Book cover and translator have been added to the /allbooks endpoint

InshAllah this could be beneficial to you

**Comment by sayyid5416** [comment]
![image](https://github.com/user-attachments/assets/41fdf896-bb46-4121-bf06-4d6a171a65da)
It's still showing old data

**Comment by MohammedArab1** [comment]
Sorry I accidentally reverted the data. 

The updated data should be there now

**Comment by sayyid5416** [comment]
Yes, now it works! Really appreciate your quick response, brother.
