### ISSUE TITLE
More fields in /allbooks endpoint 

### ISSUE THREAD

**Issue by sayyid5416** [MohammedArab1/ThaqalaynAPI#6]
Can you return book description in `/allbooks` endpoint. 

![Screenshot_20241006-123102_Edge](https://github.com/user-attachments/assets/7cd29132-f3bb-4210-a386-34f10d5b1240)

**Comment by MohammedArab1** [comment]
Salam, you should now have the book descriptions in the allbooks endpoint. Let me know if there are any issues

**Comment by sayyid5416** [comment]
Jazakallah brother! 

Is this also possible to get this distinction between text?

![Screenshot_20241007-070110_Edge](https://github.com/user-attachments/assets/1d029060-e7a7-4e29-8c33-f5da5c2f4d8a)

**Comment by sayyid5416** [comment]
Also this name would be great
![Uploading Screenshot_20241007-083759_Edge.png…]()

**Comment by sayyid5416** [comment]
Also, this name would be great to have

![Screenshot_20241007-083759_Edge](https://github.com/user-attachments/assets/e82ad1fc-e71e-454a-902c-a55ca8835cf4)

**Comment by sayyid5416** [comment]
hello! any update on this one?

**Comment by MohammedArab1** [comment]
Salam, 

I've added an "englishName" field to the allbooks endpoint and also hadiths should now have a "thaqalaynSanad" and "thaqalaynMatn" field which tries to separate the chain from the content. Please note it's far from perfect and there are issues with it, but I tried doing what I can in a short period of time.

InshAllah it's beneficial. 

WaSalam.

**Comment by sayyid5416** [comment]
Salam! Thank you for adding those. 
<Br>
> Please note it's far from perfect and there are issues with it,

Are these issues from thaqalayn side or in the scraping logic?
